version: '3'
services:
  nginx:
    build:
      context: ./nginx
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - ../ichiichiban:/var/www/laravel:cached

  php:
    build:
      context: ./phpfpm
    volumes:
      - ../ichiichiban:/var/www/laravel:cached

  mysql:
    #restart: always
    build:
      context: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
    ports:
      - 3306:3306
