---
AWSTemplateFormatVersion: 2010-09-09
Description:
  Setting up Batch Task Definition
Parameters:
  ProductName:
    Type       : String
    Description: Product Name (Ex. MansionValue)
    MinLength  : 1
  Environment:
    Type         : String
    Default      : Stg
    AllowedValues:
      - Stg
      - Prod
    Description  : Select Environment
    MinLength    : 1
  Cpu:
    Type       : Number
    Description: Hard limit on CPU for Batch containers (CPU Unit Number)
  AwsAccessKeyId:
    Type       : String
    Description: AWS ACCESS KEY ID
    MinLength  : 1
  AwsSecretAccessKey:
    Type       : String
    Description: AWS SECRET ACCESS KEY
    MinLength  : 1
  Image:
    Type       : String
    Description: Batch Image
    MinLength  : 1
  LogGroupName:
    Type       : String
    Description: Log group name
    MinLength  : 1
  Memory:
    Type       : Number
    Description: Hard limit on memory for Batch containers (MiB)
  ExecutionRoleArn:
    Type       : String
    Description: The ARN of the Task Execution Role
  TaskRoleArn:
    Type       : String
    Description: The ARN of the Task Role
  BatchContainerName:
    Type       : String
    Description: Name of Batch container
Resources:
  # ---------------------------------------------------------------#
  # Create Batch Task Definition
  # ---------------------------------------------------------------#
  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html
  BatchTaskDefinition:
    Type      : AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Cpu             : !Ref Cpu
          Environment     :
            - Name : AWS_ACCESS_KEY_ID
              Value: !Ref AwsAccessKeyId
            - Name : AWS_SECRET_ACCESS_KEY
              Value: !Ref AwsSecretAccessKey
            - Name : AWS_DEFAULT_REGION
              Value: ap-northeast-1
          Image           : !Ref Image
          LogConfiguration:
            LogDriver: awslogs
            Options  :
              awslogs-group        : !Ref LogGroupName
              awslogs-region       : ap-northeast-1
              awslogs-stream-prefix: batch
          Memory          : !Ref Memory
          Name            : !Ref BatchContainerName
      ExecutionRoleArn    : !Ref ExecutionRoleArn
      Family              : !Sub "${ProductName}-${Environment}-Batch"
      TaskRoleArn         : !Ref TaskRoleArn
Outputs:
  BatchTaskDefinitionArn:
    Description: The ARN of the Batch Task Definition
    Value      : !Ref BatchTaskDefinition