---
AWSTemplateFormatVersion: 2010-09-09
Description:
  Setting up Refresh Data Batch Task Definition
Parameters:
  ProductName:
    Type       : String
    Description: Product Name (Ex. MansionValue)
    MinLength  : 1
  Environment:
    Type         : String
    Default      : Stg
    AllowedValues:
      - Stg
      - Prod
    Description  : Select Environment
    MinLength    : 1
  Cpu:
    Type       : Number
    Description: Hard limit on CPU for Batch containers (CPU Unit Number)
  Image:
    Type       : String
    Description: Refresh Data Batch Image
    MinLength  : 1
  LogGroupName:
    Type       : String
    Description: Log group name
    MinLength  : 1
  Memory:
    Type       : Number
    Description: Hard limit on memory for Batch containers (MiB)
  ExecutionRoleArn:
    Type       : String
    Description: The ARN of the Task Execution Role
  TaskRoleArn:
    Type       : String
    Description: The ARN of the Task Role
  RefreshDataBatchContainerName:
    Type       : String
    Description: Name of Refresh Data Batch container
Resources:
  # ---------------------------------------------------------------#
  # Create Refresh Data Batch Task Definition
  # ---------------------------------------------------------------#
  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html
  RefreshDataBatchTaskDefinition:
    Type      : AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Command         : [ "/bin/sh", "-c", "./refresh-data/build/refresh-data -c ./refresh-data/conf/connect.json" ]
          Cpu             : !Ref Cpu
          Image           : !Ref Image
          LogConfiguration:
            LogDriver: awslogs
            Options  :
              awslogs-group        : !Ref LogGroupName
              awslogs-region       : ap-northeast-1
              awslogs-stream-prefix: refresh-data-batch
          Memory          : !Ref Memory
          Name            : !Ref RefreshDataBatchContainerName
      ExecutionRoleArn    : !Ref ExecutionRoleArn
      Family              : !Sub "${ProductName}-${Environment}-RefreshDataBatch"
      TaskRoleArn         : !Ref TaskRoleArn
Outputs:
  RefreshDataBatchTaskDefinitionArn:
    Description: The ARN of the Refresh Data Batch Task Definition
    Value      : !Ref RefreshDataBatchTaskDefinition