---
AWSTemplateFormatVersion: 2010-09-09
Description:
  Setting up Web Task Definition
Parameters:
  ProductName:
    Type       : String
    Description: Product Name (Ex. MansionValue)
    MinLength  : 1
  Environment:
    Type         : String
    Default      : Stg
    AllowedValues:
      - Stg
      - Prod
    Description  : Select Environment
    MinLength    : 1
  Cpu:
    Type       : Number
    Description: Hard limit on CPU for Web containers (CPU Unit Number)
  Image:
    Type       : String
    Description: Web Image
    MinLength  : 1
  LogGroupName:
    Type       : String
    Description: Log group name
    MinLength  : 1
  Memory:
    Type       : Number
    Description: Hard limit on memory for Web containers (MiB)
  ExecutionRoleArn:
    Type       : String
    Description: The ARN of the Task Execution Role
  TaskRoleArn:
    Type       : String
    Description: The ARN of the Task Role
  WebContainerName:
    Type       : String
    Description: Name of Web container
  WebContainerPort:
    Type       : String
    Description: Port of Web container
Resources:
  # ---------------------------------------------------------------#
  # Create Web Task Definition
  # ---------------------------------------------------------------#
  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html
  WebTaskDefinition:
    Type      : AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Cpu             : !Ref Cpu
          Image           : !Ref Image
          LogConfiguration:
            LogDriver: awslogs
            Options  :
              awslogs-group        : !Ref LogGroupName
              awslogs-region       : ap-northeast-1
              awslogs-stream-prefix: web
          Memory          : !Ref Memory
          Name            : !Ref WebContainerName
          PortMappings    :
            - ContainerPort: !Ref WebContainerPort
              HostPort     : 0
      ExecutionRoleArn    : !Ref ExecutionRoleArn
      Family              : !Sub "${ProductName}-${Environment}-Web"
      TaskRoleArn         : !Ref TaskRoleArn
Outputs:
  WebTaskDefinitionArn:
    Description: The ARN of the Web Task Definition
    Value      : !Ref WebTaskDefinition