AWSTemplateFormatVersion: 2010-09-09
Description: Create workload
Parameters:
  Environment:
    Type: String
    Default: Prod
    AllowedValues:
    - Stg
    - Prod
    Description: Select Environment
    MinLength: 1
  MasterUsername:
    Type: String
    Description: RDS Master User Name
    MinLength: 1
  MasterUserPassword:
    Type: String
    Description: RDS Master User Passwordf
    MinLength: 1
  LogGroupRetentionInDays:
    Type: Number
    Description: Number of days to keep logs
    MinValue: 3
    Default: 3
  Ec2InstanceType:
    Type: String
    Description: EC2 Instance Type
    Default: t2.micro
    MinLength: 1
  Ec2AutoScalingGroupMinSize:
    Type: Number
    Description: Min size of EC2 Auto Scaling Group
    MinValue: 1
    Default: 1
  Ec2AutoScalingGroupMaxSize:
    Type: Number
    Description: Max size of EC2 Auto Scaling Group
    MinValue: 1
    Default: 1
  Ec2AutoScalingGroupDesiredCapacity:
    Type: Number
    Description: Desired capacity of EC2 Auto Scaling Group
    MinValue: 1
    Default: 1
  WebCpu:
    Type: Number
    Description: Hard limit of CPU for Web containers
    MinValue: 256
    Default: 256
  WebMemory:
    Type: Number
    Description: Hard limit of memory for Web containers (MiB)
    MinValue: 512
    Default: 512
  WebDesiredCount:
    Type: Number
    Description: Desired Count of Web Task
    MinValue: 1
    Default: 1
  ApiCpu:
    Type: Number
    Description: Hard limit of CPU for Api containers
    MinValue: 256
    Default: 256
  ApiMemory:
    Type: Number
    Description: Hard limit of memory for Api containers (MiB)
    MinValue: 1024
    Default: 1024
  ApiDesiredCount:
    Type: Number
    Description: Desired Count of Api Task
    MinValue: 1
    Default: 1
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Common Configuration
      Parameters:
      - Environment
    - Label:
        default: Database Configuration
      Parameters:
      - MasterUsername
      - MasterUserPassword
    - Label:
        default: Log Configuration
      Parameters:
      - LogGroupRetentionInDays
    - Label:
        default: EC2 Auto Scaling Group Configuration
      Parameters:
      - Ec2InstanceType
      - Ec2AutoScalingGroupMinSize
      - Ec2AutoScalingGroupMaxSize
      - Ec2AutoScalingGroupDesiredCapacity
    - Label:
        default: ECS Configuration
      Parameters:
      - WebCpu
      - WebMemory
      - WebDesiredCount
      - ApiCpu
      - ApiMemory
      - ApiDesiredCount
Mappings:
  Ec2AutoScaling:
    Stg:
      EC2KeyName: stg-ichiichiban
    Prod:
      EC2KeyName: prod-ichiichiban
Resources:
  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProductName: IchiIchiban
        Environment:
          Ref: Environment
        VpcId:
          Fn::ImportValue:
            Fn::Sub: IchiIchiban-${Environment}-VpcId
      Tags:
      - Key: Name
        Value:
          Fn::Sub: IchiIchiban-${Environment}
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/ichiichiban-cloudformation-template/248e10756231ab46770331b266e96676.template
  RDS:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProductName: IchiIchiban
        Environment:
          Ref: Environment
        DBParameterGroupFamily: mysql8.0
        DBMasterInstanceClass: db.t2.micro
        PrivateSubnetIds:
          Fn::Join:
          - ','
          - - Fn::ImportValue:
                Fn::Sub: IchiIchiban-${Environment}-PrivateSubnetAId
            - Fn::ImportValue:
                Fn::Sub: IchiIchiban-${Environment}-PrivateSubnetCId
        Engine: mysql
        EngineVersion: 8.0.16
        MasterUsername:
          Ref: MasterUsername
        MasterUserPassword:
          Ref: MasterUserPassword
        MonitoringRoleArn:
          Fn::ImportValue: RDSMonitoringRoleArn
        RdsSecurityGroupIds:
          Fn::Join:
          - ','
          - - Fn::GetAtt:
              - SecurityGroups
              - Outputs.RdsSecurityGroupId
      Tags:
      - Key: Name
        Value:
          Fn::Sub: IchiIchiban-${Environment}
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/ichiichiban-cloudformation-template/19b7d7d75a8f332569235d3f5cc33aba.template
