---
# ---------------------------------------------------------------#
# Create Roles
#   - Allowing ECS calls in CloudWatch Role
#   - Allowing ECS calls in EC2 Role
#   - Application auto scaling in ECS Role
#   - ECS instance profile
#   - RDS Monitoring Role
#   - Task Execution Role
# ---------------------------------------------------------------#
AWSTemplateFormatVersion: 2010-09-09
Description:
  Create Roles
Resources:
  CloudWatchEventEcsRole:
    Type      : AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./roles/cloudwatch-event-ecs-role.yml
  EC2ECSRole:
    Type      : AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./roles/ec2-ecs-role.yml
  ECSAutoScaleRole:
    Type      : AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./roles/ecs-application-autoscaling-role.yml
  EcsInstanceProfileRole:
    Type      : AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./roles/ecs-instance-profile-role.yml
  LambdaBasicExecutionRole:
    Type      : AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./roles/lambda-basic-execution-role.yml
  RDSMonitoringRole:
    Type      : AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./roles/rds-monitoring-role.yml
  TaskExecutionRole:
    Type      : AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./roles/task-execution-role.yml