---
# ---------------------------------------------------------------#
# https://github.com/aws-samples/aws-cloudfront-samples/tree/master/update_security_groups_lambda
# ---------------------------------------------------------------#
AWSTemplateFormatVersion: 2010-09-09
Description:
  Create update_security_groups_lambda
Resources:
  # ---------------------------------------------------------------#
  # Create Role
  # ---------------------------------------------------------------#
  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
  UpdateCloudFrontSecurityGroupsRole:
    Type      : AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version  : "2012-10-17"
        Statement:
          - Effect   : Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName    : root
          PolicyDocument:
            Version  : "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:AuthorizeSecurityGroupIngress"
                  - "ec2:RevokeSecurityGroupIngress"
                Resource: !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:security-group/*"
              - Effect: Allow
                Action:
                  - "ec2:DescribeSecurityGroups"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
  # ---------------------------------------------------------------#
  # Create Lambda
  # ---------------------------------------------------------------#
  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html
  UpdateCloudFrontSecurityGroupsLambda:
    Type      : AWS::Lambda::Function
    Properties:
      Code        : ./lambda-function
      Description : Update CloudFront Security Groups
      FunctionName: UpdateCloudFrontSecurityGroups
      Handler     : update_security_groups.lambda_handler
      Role        : !GetAtt UpdateCloudFrontSecurityGroupsRole.Arn
      Runtime     : python2.7
      Tags        :
        - Key  : Name
          Value: UpdateCloudFrontSecurityGroups
      Timeout     : 60