---
AWSTemplateFormatVersion: 2010-09-09
Description:
  Setting up RDS
Parameters:
  ProductName:
    Type       : String
    Description: Product Name (Ex. MansionValue)
    MinLength  : 1
  Environment:
    Type         : String
    Default      : Stg
    AllowedValues:
      - Stg
      - Prod
    Description  : Select Environment
    MinLength    : 1
  DBParameterGroupFamily:
    Type         : String
    Description  : Family for DB Cluster Parameter Group
    Default      : mysql8.0
    AllowedValues:
      [ aurora-mysql5.7,
        aurora-postgresql9.6, aurora-postgresql10,
        mariadb10.0, mariadb10.1, mariadb10.2, mariadb10.3,
        mysql5.5, mysql5.6, mysql5.7, mysql8.0,
        oracle-ee-11.2, oracle-ee-12.1, oracle-ee-12.2, oracle-ee-18,
        oracle-se-11.2, oracle-se1-11.2, oracle-se2-12.1, oracle-se2-12.2, oracle-se2-18,
        aurora5.6,
        postgres9.3, postgres9.4, postgres9.5, postgres9.6, postgres10, postgres11,
        sqlserver-ee-11.0, sqlserver-ee-12.0, sqlserver-ee-13.0, sqlserver-ee-14.0,
        sqlserver-ex-11.0, sqlserver-ex-12.0, sqlserver-ex-13.0, sqlserver-ex-14.0,
        sqlserver-se-11.0, sqlserver-se-12.0, sqlserver-se-13.0, sqlserver-se-14.0,
        sqlserver-web-11.0, sqlserver-web-12.0, sqlserver-web-13.0, sqlserver-web-14.0 ]
    MinLength    : 1
  DBMasterInstanceClass:
    Type         : String
    Description  : RDS Master Instance Class
    MinLength    : 1
    Default      : db.t2.micro
  PrivateSubnetIds:
    Type       : List<AWS::EC2::Subnet::Id>
    Description: Private Subnet IDs
    MinLength  : 1
  Engine:
    Type         : String
    Description  : Database Engine
    Default      : mysql
    MinLength    : 1
  EngineVersion:
    Type         : String
    Description  : Database Engine Version
    MinLength    : 1
  MasterUsername:
    Type       : String
    Description: Master User Name
    MinLength  : 1
  MasterUserPassword:
    Type       : String
    Description: Master User Password
    MinLength  : 1
  MonitoringRoleArn:
    Type       : String
    Description: RDS Monitoring Role ARN
    MinLength  : 1
  RdsSecurityGroupIds:
    Type       : List<AWS::EC2::SecurityGroup::Id>
    Description: RDS Security Group IDs
    MinLength  : 1
Mappings:
  RDS:
    Stg :
      BackupRetentionPeriod: 3
      DeletionProtection   : false
    Prod:
      BackupRetentionPeriod: 7
      DeletionProtection   : true
Resources:
  # ---------------------------------------------------------------#
  # Create DB parameter group
  # ---------------------------------------------------------------#
  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-rds-dbparametergroup.html
  DBParameterGroup:
    Type      : AWS::RDS::DBParameterGroup
    Properties:
      Description: !Sub "DB Parameter Group of ${ProductName}-${Environment}"
      Family     : !Ref DBParameterGroupFamily
      Parameters :
        character_set_client    : "utf8mb4"
        character_set_connection: "utf8mb4"
        character_set_database  : "utf8mb4"
        character_set_filesystem: "utf8mb4"
        character_set_results   : "utf8mb4"
        character_set_server    : "utf8mb4"
        collation_connection    : "utf8mb4_bin"
        collation_server        : "utf8mb4_bin"
        time_zone               : "Asia/Tokyo"
  # ---------------------------------------------------------------#
  # Create DB subnet group
  # ---------------------------------------------------------------#
  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbsubnet-group.html
  DBSubnetGroup:
    Type      : AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub "Subnet Group of ${ProductName}-${Environment}"
      SubnetIds               : !Ref PrivateSubnetIds
  # ---------------------------------------------------------------#
  # Create DB Instances
  # ---------------------------------------------------------------#
  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html
  DBMasterInstance:
    Type      : AWS::RDS::DBInstance
    Properties:
      AllocatedStorage     : 20
      AvailabilityZone     : ap-northeast-1a
      BackupRetentionPeriod: !FindInMap [ RDS, !Ref Environment, BackupRetentionPeriod ]
      DBInstanceClass      : !Ref DBMasterInstanceClass
      DBParameterGroupName : !Ref DBParameterGroup
      DBSubnetGroupName    : !Ref DBSubnetGroup
      DeletionProtection   : !FindInMap [ RDS, !Ref Environment, DeletionProtection ]
      Engine               : !Ref Engine
      EngineVersion        : !Ref EngineVersion
      MasterUsername       : !Ref MasterUsername
      MasterUserPassword   : !Ref MasterUserPassword
      MonitoringInterval   : 60
      MonitoringRoleArn    : !Ref MonitoringRoleArn
      Port                 : 3306
      PubliclyAccessible   : false
      VPCSecurityGroups    : !Ref RdsSecurityGroupIds
Outputs:
  DBMasterInstanceEndpoint:
    Description: The Endpoint of the master DB
    Value      : !GetAtt DBMasterInstance.Endpoint.Address