---
AWSTemplateFormatVersion: 2010-09-09
Description:
  Setting up ECS Web Services
Parameters:
  ProductName:
    Type       : String
    Description: Product Name (Ex. MansionValue)
    MinLength  : 1
  Environment:
    Type         : String
    Default      : Stg
    AllowedValues:
      - Stg
      - Prod
    Description  : Select Environment
    MinLength    : 1
  BatchCpu:
    Type       : Number
    Description: Hard limit on CPU for Batch containers (CPU Unit Number)
    MinValue   : 256
  BatchMemory:
    Type       : Number
    Description: Hard limit of memory for Batch containers (MiB)
    MinValue   : 1024
  LogGroupName:
    Type       : String
    Description: Log group name
    MinLength  : 1
  ScheduleExpression:
    Type       : String
    Description: Cron settings
    MinLength  : 1
  ECSClusterArn:
    Type       : String
    Description: ECS Cluster ARN
    MinLength  : 1
  ExecutionRoleArn:
    Type       : String
    Description: The ARN of the Task Execution Role
    MinLength  : 1
  TaskRoleArn:
    Type       : String
    Description: Task Role ARN
    MinLength  : 1
  CloudWatchEventEcsRoleArn:
    Type       : String
    Description: CloudWatch Event ECS Role ARN
    MinLength  : 1
Mappings:
  BatchEcs:
    Stg :
      AwsAccessKeyId    : AKIA5GBGJMWU6ZTEJXXM
      AwsSecretAccessKey: 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
      Image             : 906318407081.dkr.ecr.ap-northeast-1.amazonaws.com/realnetplus-stg-batch:latest
    Prod:
      AwsAccessKeyId    : AKIA5GBGJMWUQINPOLNE
      AwsSecretAccessKey: 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
      Image             : 906318407081.dkr.ecr.ap-northeast-1.amazonaws.com/realnetplus-prod-batch:latest
Resources:
  # ---------------------------------------------------------------#
  # Create Manual Execution Batch Task Definition
  #   - Sync Cooperation Data Batch
  #   - Refresh Data Batch
  # ---------------------------------------------------------------#
  SyncCooperationDataBatchTaskDefinition:
    Type      : AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProductName                          : !Ref ProductName
        Environment                          : !Ref Environment
        Cpu                                  : !Ref BatchCpu
        AwsAccessKeyId                       : !FindInMap [ BatchEcs, !Ref Environment, AwsAccessKeyId ]
        AwsSecretAccessKey                   : !FindInMap [ BatchEcs, !Ref Environment, AwsSecretAccessKey ]
        Image                                : !FindInMap [ BatchEcs, !Ref Environment, Image ]
        LogGroupName                         : !Ref LogGroupName
        Memory                               : !Ref BatchMemory
        ExecutionRoleArn                     : !Ref ExecutionRoleArn
        TaskRoleArn                          : !Ref TaskRoleArn
        SyncCooperationDataBatchContainerName: SyncCooperationDataBatch
      TemplateURL: ./task-definitions/sync-cooperation-data-batch.yml
  RefreshDataBatchTaskDefinition:
    Type      : AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProductName                  : !Ref ProductName
        Environment                  : !Ref Environment
        Cpu                          : !Ref BatchCpu
        Image                        : !FindInMap [ BatchEcs, !Ref Environment, Image ]
        LogGroupName                 : !Ref LogGroupName
        Memory                       : !Ref BatchMemory
        ExecutionRoleArn             : !Ref ExecutionRoleArn
        TaskRoleArn                  : !Ref TaskRoleArn
        RefreshDataBatchContainerName: SyncCooperationDataBatch
      TemplateURL: ./task-definitions/refresh-data-batch.yml
  # ---------------------------------------------------------------#
  # Create Batch Task Definition
  # ---------------------------------------------------------------#
  BatchTaskDefinition:
    Type      : AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProductName       : !Ref ProductName
        Environment       : !Ref Environment
        Cpu               : !Ref BatchCpu
        AwsAccessKeyId    : !FindInMap [ BatchEcs, !Ref Environment, AwsAccessKeyId ]
        AwsSecretAccessKey: !FindInMap [ BatchEcs, !Ref Environment, AwsSecretAccessKey ]
        Image             : !FindInMap [ BatchEcs, !Ref Environment, Image ]
        LogGroupName      : !Ref LogGroupName
        Memory            : !Ref BatchMemory
        ExecutionRoleArn  : !Ref ExecutionRoleArn
        TaskRoleArn       : !Ref TaskRoleArn
        BatchContainerName: Batch
      TemplateURL: ./task-definitions/batch.yml
  # ---------------------------------------------------------------#
  # Create Event Rule
  # ---------------------------------------------------------------#
  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html
  EcsBatchTaskSchedule:
    Type      : AWS::Events::Rule
    Properties:
      Description       : !Sub "${ProductName}-${Environment} Batch Task Schedule"
      Name              : !Sub "${ProductName}-${Environment}-Batch-TaskSchedule"
      ScheduleExpression: !Ref ScheduleExpression
      State             : ENABLED
      Targets           :
        - Arn          : !Ref ECSClusterArn
          EcsParameters:
            TaskCount        : 1
            TaskDefinitionArn: !GetAtt BatchTaskDefinition.Outputs.BatchTaskDefinitionArn
          Id           : !Sub "${ProductName}-${Environment}-Batch-TaskSchedule"
          RoleArn      : !Ref CloudWatchEventEcsRoleArn