---
AWSTemplateFormatVersion: 2010-09-09
Description:
  Setting up ECS Web Services
Parameters:
  ProductName:
    Type       : String
    Description: Product Name (Ex. MansionValue)
    MinLength  : 1
  Environment:
    Type         : String
    Default      : Stg
    AllowedValues:
      - Stg
      - Prod
    Description  : Select Environment
    MinLength    : 1
  WebCpu:
    Type       : Number
    Description: Hard limit on CPU for Web containers (CPU Unit Number)
    MinValue   : 256
  WebMemory:
    Type       : Number
    Description: Hard limit of memory for Web containers (MiB)
    MinValue   : 512
  LogGroupName:
    Type       : String
    Description: Log group name
    MinLength  : 1
  ExecutionRoleArn:
    Type       : String
    Description: Task Execution Role ARN
    MinLength  : 1
  TaskRoleArn:
    Type       : String
    Description: Task Role ARN
    MinLength  : 1
  ECSCluster:
    Type       : String
    Description: ECS Cluster Name
    MinLength  : 1
  WebDesiredCount:
    Type       : Number
    Description: Desired Count of Web Task
    MinValue   : 1
  TargetGroupArn:
    Type       : String
    Description: Target Group ARN
    MinLength  : 1
  ECSAutoScaleRoleArn:
    Type       : String
    Description: ECS Auto Scale Role ARN
    MinLength  : 1
Mappings:
  WebEcs:
    Stg :
      Image:
    Prod:
      Image:
Resources:
  # ---------------------------------------------------------------#
  # Create Web Task Definition
  # ---------------------------------------------------------------#
  WebTaskDefinition:
    Type      : AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProductName     : !Ref ProductName
        Environment     : !Ref Environment
        Cpu             : !Ref WebCpu
        Image           : !FindInMap [ WebEcs, !Ref Environment, Image ]
        LogGroupName    : !Ref LogGroupName
        Memory          : !Ref WebMemory
        ExecutionRoleArn: !Ref ExecutionRoleArn
        TaskRoleArn     : !Ref TaskRoleArn
        WebContainerName: Web
        WebContainerPort: 80
      TemplateURL: ./task-definitions/web.yml
  # ---------------------------------------------------------------#
  # Create Web Service
  # ---------------------------------------------------------------#
  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html
  ECSWebService:
    Type      : AWS::ECS::Service
    Properties:
      Cluster       : !Ref ECSCluster
      DesiredCount  : !Ref WebDesiredCount
      LaunchType    : EC2
      LoadBalancers :
        - ContainerName : Web
          ContainerPort : 80
          TargetGroupArn: !Ref TargetGroupArn
      ServiceName   : !Sub "${ProductName}-${Environment}-Web"
      TaskDefinition: !GetAtt WebTaskDefinition.Outputs.WebTaskDefinitionArn
  # ---------------------------------------------------------------#
  # Create Web Service Auto Scaling
  # ---------------------------------------------------------------#
  ECSWebServiceAutoScaling:
    Type      : AWS::CloudFormation::Stack
    Properties:
      Parameters:
        WebTaskMaxCapacity : 40 # 4GiB(4096MiB) / 512MiB(Webコンテナのメモリ) * 5台 = 40
        WebTaskMinCapacity : 2
        ECSCluster         : !Ref ECSCluster
        ECSWebServiceName  : !GetAtt ECSWebService.Name
        ECSAutoScaleRoleArn: !Ref ECSAutoScaleRoleArn
        CPUTargetValue     : 70
        MemoryTargetValue  : 70
      Tags:
        - Key  : Name
          Value: !Sub "RealnetPlus-${Environment}"
      TemplateURL: ./ecs-auto-scaling/web-service-auto-scaling.yml