---
AWSTemplateFormatVersion: 2010-09-09
Description:
  Setting up EC2 Auto Scaling abnormality notification
Parameters:
  ProductName:
    Type       : String
    Description: Product Name (Ex. MansionValue)
    MinLength  : 1
  Environment:
    Type         : String
    Default      : Stg
    AllowedValues:
      - Stg
      - Prod
    Description  : Select Environment
    MinLength    : 1
Resources:
  # ---------------------------------------------------------------#
  # Create EC2 Auto Scaling Group SNS Topic
  # ---------------------------------------------------------------#
  Ec2AutoScalingGroupSnsTopic:
    Type      : AWS::CloudFormation::Stack
    Properties:
      Parameters:
        TopicDisplayName: !Sub "${ProductName}-${Environment} EC2 Auto Scaling Group"
        TopicName       : !Sub "${ProductName}-${Environment}-EC2-Auto-Scaling-Group-Topic"
      TemplateURL: ./../../sns/topic.yml
  # ---------------------------------------------------------------#
  # Create EC2 Auto Scaling Group Slack notification Lambda
  # ---------------------------------------------------------------#
  Ec2AutoScalingGroupSlackNotificationLambdaExecutionRole:
    Type      : AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./slack-notification-lambda/lambda-execution-role.yml
  Ec2AutoScalingGroupSlackNotificationLambda:
    Type      : AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Environment           : !Ref Environment
        LambdaCode            : "./../ec2-auto-scaling/lambda-function"
        LambdaDescription     : !Sub "${ProductName}-${Environment} EC2 Auto Scaling Group Slack Notification Lambda"
        LambdaHandler         : realnetplus-ec2-auto-scaling-slack-notification.lambda_handler
        LambdaExecutionRoleArn: !GetAtt Ec2AutoScalingGroupSlackNotificationLambdaExecutionRole.Outputs.LambdaExecutionRoleArn
        TopicArn              : !GetAtt Ec2AutoScalingGroupSnsTopic.Outputs.SnsTopicArn
      TemplateURL: ./../../sns/slack-notification-lambda-function.yml
  # ---------------------------------------------------------------#
  # Create EC2 Auto Scaling Group SNS Subscription
  # ---------------------------------------------------------------#
  Ec2AutoScalingGroupLambdaSubscription:
    Type      : AWS::CloudFormation::Stack
    Properties:
      Parameters:
        LambdaArn: !GetAtt Ec2AutoScalingGroupSlackNotificationLambda.Outputs.Ec2AutoScalingGroupSlackNotificationLambdaFunctionArn
        TopicArn : !GetAtt Ec2AutoScalingGroupSnsTopic.Outputs.SnsTopicArn
      TemplateURL: ./../../sns/lambda-subscription.yml
Outputs:
  Ec2AutoScalingGroupSnsTopicArn:
    Description: The ARN of EC2 Auto Scaling Group SNS topic
    Value      : !GetAtt Ec2AutoScalingGroupSnsTopic.Outputs.SnsTopicArn
  Ec2AutoScalingGroupSnsTopicName:
    Description: The Name of EC2 Auto Scaling Group SNS topic
    Value      : !GetAtt Ec2AutoScalingGroupSnsTopic.Outputs.SnsTopicName
  Ec2AutoScalingGroupSlackNotificationLambdaFunctionName:
    Description: The name of EC2 Auto Scaling Group slack notification lambda
    Value      : !GetAtt Ec2AutoScalingGroupSlackNotificationLambda.Outputs.Ec2AutoScalingGroupSlackNotificationLambdaFunctionName
  Ec2AutoScalingGroupSlackNotificationLambdaFunctionArn:
    Description: The ARN of EC2 Auto Scaling Group slack notification lambda
    Value      : !GetAtt Ec2AutoScalingGroupSlackNotificationLambda.Outputs.Ec2AutoScalingGroupSlackNotificationLambdaFunctionArn