---
AWSTemplateFormatVersion: 2010-09-09
Description:
  Setting up EC2 Auto Scaling
Parameters:
  ProductName:
    Type       : String
    Description: Product Name (Ex. MansionValue)
    MinLength  : 1
  Environment:
    Type         : String
    Default      : Stg
    AllowedValues:
      - Stg
      - Prod
    Description  : Select Environment
    MinLength    : 1
  IamInstanceProfileRoles:
    Type       : String
    Description: Comma delimited roles for EC2Instance
    MinLength  : 1
  DeviceName:
    Type       : String
    Default    : /dev/xvda
    Description: Device Name for EBS
    MinLength  : 1
  VolumeSize:
    Type       : Number
    Default    : 8
    Description: EBS Volume size in gigabinary bytes (GiB)
    MinValue   : 8
  VolumeType:
    Type       : String
    Default    : gp2
    Description: EBS Volume type
    MinLength  : 1
  ImageId:
    Type       : AWS::EC2::Image::Id
    Description: Image ID for instances
    MinLength  : 1
  InstanceType:
    Type       : String
    Description: Instance type for instances
    Default    : t3.small
    AllowedValues:
      [ a1.2xlarge, a1.4xlarge, a1.large, a1.medium, a1.xlarge,
        c1.medium, c1.xlarge, c3.2xlarge, c3.4xlarge, c3.8xlarge, c3.large, c3.xlarge,
        c4.2xlarge, c4.4xlarge, c4.8xlarge, c4.large, c4.xlarge, c5.12xlarge,
        c5.18xlarge, c5.24xlarge, c5.2xlarge, c5.4xlarge, c5.9xlarge, c5.large, c5.xlarge,
        c5d.18xlarge, c5d.2xlarge, c5d.4xlarge, c5d.9xlarge, c5d.large, c5d.xlarge,
        c5n.18xlarge, c5n.2xlarge, c5n.4xlarge, c5n.9xlarge, c5n.large, c5n.xlarge,
        cc1.4xlarge, cc2.8xlarge, cg1.4xlarge, cr1.8xlarge,
        d2.2xlarge, d2.4xlarge, d2.8xlarge, d2.xlarge,
        f1.16xlarge, f1.2xlarge, f1.4xlarge,
        g2.2xlarge, g2.8xlarge, g3.16xlarge, g3.4xlarge, g3.8xlarge, g3s.xlarge,
        h1.16xlarge, h1.2xlarge, h1.4xlarge, h1.8xlarge, hi1.4xlarge, hs1.8xlarge,
        i2.2xlarge, i2.4xlarge, i2.8xlarge, i2.xlarge,
        i3.16xlarge, i3.2xlarge, i3.4xlarge, i3.8xlarge, i3.large, i3.metal, i3.xlarge,
        i3en.12xlarge, i3en.24xlarge, i3en.2xlarge, i3en.3xlarge, i3en.6xlarge, i3en.large, i3en.xlarge,
        m1.large, m1.medium, m1.small, m1.xlarge,
        m2.2xlarge, m2.4xlarge, m2.xlarge,
        m3.2xlarge, m3.large, m3.medium, m3.xlarge,
        m4.10xlarge, m4.16xlarge, m4.2xlarge, m4.4xlarge, m4.large, m4.xlarge,
        m5.12xlarge, m5.24xlarge, m5.2xlarge, m5.4xlarge, m5.large, m5.metal, m5.xlarge,
        m5a.12xlarge, m5a.24xlarge, m5a.2xlarge, m5a.4xlarge, m5a.large, m5a.xlarge,
        m5ad.12xlarge, m5ad.16xlarge, m5ad.24xlarge, m5ad.2xlarge, m5ad.4xlarge, m5ad.8xlarge, m5ad.large, m5ad.xlarge,
        m5d.12xlarge, m5d.24xlarge, m5d.2xlarge, m5d.4xlarge, m5d.large, m5d.metal, m5d.xlarge,
        p2.16xlarge, p2.8xlarge, p2.xlarge, p3.16xlarge, p3.2xlarge, p3.8xlarge, p3dn.24xlarge,
        r3.2xlarge, r3.4xlarge, r3.8xlarge, r3.large, r3.xlarge,
        r4.16xlarge, r4.2xlarge, r4.4xlarge, r4.8xlarge, r4.large, r4.xlarge,
        r5.12xlarge, r5.24xlarge, r5.2xlarge, r5.4xlarge, r5.large, r5.metal, r5.xlarge,
        r5a.12xlarge, r5a.24xlarge, r5a.2xlarge, r5a.4xlarge, r5a.large, r5a.xlarge,
        r5ad.12xlarge, r5ad.16xlarge, r5ad.24xlarge, r5ad.2xlarge, r5ad.4xlarge, r5ad.8xlarge, r5ad.large, r5ad.xlarge,
        r5d.12xlarge, r5d.24xlarge, r5d.2xlarge, r5d.4xlarge, r5d.large, r5d.metal, r5d.xlarge,
        t1.micro, t2.2xlarge, t2.large, t2.medium, t2.micro, t2.nano, t2.small, t2.xlarge,
        t3.2xlarge, t3.large, t3.medium, t3.micro, t3.nano, t3.small, t3.xlarge,
        t3a.2xlarge, t3a.large, t3a.medium, t3a.micro, t3a.nano, t3a.small, t3a.xlarge,
        u-12tb1.metal, u-6tb1.metal, u-9tb1.metal,
        x1.16xlarge, x1.32xlarge, x1e.16xlarge, x1e.2xlarge, x1e.32xlarge, x1e.4xlarge, x1e.8xlarge, x1e.xlarge,
        z1d.12xlarge, z1d.2xlarge, z1d.3xlarge, z1d.6xlarge, z1d.large, z1d.metal, z1d.xlarge ]
    MinLength  : 1
  KeyName:
    Type       : AWS::EC2::KeyPair::KeyName
    Description: Key Pair Name of instances
    MinLength  : 1
  SecurityGroupIds:
    Type       : List<AWS::EC2::SecurityGroup::Id>
    Description: Security Group IDs for instances
    MinLength  : 1
  UserDataContent:
    Type       : String
    Description: User data content for instances
    MinLength  : 1
  MinSize:
    Type       : Number
    Default    : 1
    Description: Minimum number of instances that can be launched in your ECS cluster.
    MinValue   : 1
  MaxSize:
    Type       : Number
    Default    : 1
    Description: Maximum number of instances that can be launched in your ECS cluster.
    MinValue   : 1
  DesiredCapacity:
    Type       : Number
    Default    : 1
    Description: Number of instances to launch in your ECS cluster.
    MinValue   : 1
  PublicSubnetIds:
    Type       : List<AWS::EC2::Subnet::Id>
    Description: Public Subnet IDs
    MinLength  : 1
  ClusterName:
    Type       : String
    Description: ECS Cluster Name
    MinLength  : 1
Resources:
  # ---------------------------------------------------------------#
  # Create EC2 Auto Scaling Group Notification Action (SNS Topic and Subscription)
  # ---------------------------------------------------------------#
  Ec2AutoScalingGroupSns:
    Type      : AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProductName    : !Ref ProductName
        Environment    : !Ref Environment
      TemplateURL: ./sns/sns.yml
  # ---------------------------------------------------------------#
  # Create EC2 Auto Scaling Group Launch Configuration
  # ---------------------------------------------------------------#
  Ec2AutoScalingGroupLaunchConfiguration:
    Type      : AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProductName            : !Ref ProductName
        Environment            : !Ref Environment
        IamInstanceProfileRoles: !Ref IamInstanceProfileRoles
        DeviceName             : !Ref DeviceName
        VolumeSize             : !Ref VolumeSize
        VolumeType             : !Ref VolumeType
        ImageId                : !Ref ImageId
        InstanceType           : !Ref InstanceType
        KeyName                : !Ref KeyName
        SecurityGroupIds       :
          !Join
            - ","
            - !Ref SecurityGroupIds
        UserDataContent        : !Ref UserDataContent
      TemplateURL: ./launch-configuration.yml
  # ---------------------------------------------------------------#
  # Create EC2 Auto Scaling Group
  # ---------------------------------------------------------------#
  Ec2AutoScalingGroup:
    Type      : AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProductName            : !Ref ProductName
        Environment            : !Ref Environment
        LaunchConfigurationName: !GetAtt Ec2AutoScalingGroupLaunchConfiguration.Outputs.LaunchConfigurationName
        MinSize                : !Ref MinSize
        MaxSize                : !Ref MaxSize
        DesiredCapacity        : !Ref DesiredCapacity
        TopicARN               : !GetAtt Ec2AutoScalingGroupSns.Outputs.Ec2AutoScalingGroupSnsTopicArn
        PublicSubnetIds        : !Ref PublicSubnetIds
      TemplateURL: ./ec2-auto-scaling-group.yml
  # ---------------------------------------------------------------#
  # Create EC2 Auto Scaling Group SNS Topic Policy
  # ---------------------------------------------------------------#
  Ec2AutoScalingGroupSnsTopicPolicy:
    Type      : AWS::CloudFormation::Stack
    Properties:
      Parameters:
        TopicArn              : !GetAtt Ec2AutoScalingGroupSns.Outputs.Ec2AutoScalingGroupSnsTopicArn
        Ec2AutoScalingGroupArn: !Sub "arn:aws:autoscaling:region:${AWS::Region}:autoScalingGroup:${AWS::AccountId}:autoScalingGroupName/${Ec2AutoScalingGroup.Outputs.Ec2AutoScalingGroupName}"
      TemplateURL: ./sns/topic-policy.yml
  # ---------------------------------------------------------------#
  # Create EC2 Auto Scaling Group Scaling Policy
  # ---------------------------------------------------------------#
  Ec2AutoScalingGroupScalingPolicy:
    Type      : AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AutoScalingGroupName: !GetAtt Ec2AutoScalingGroup.Outputs.AutoScalingGroupName
        ClusterName         : !Ref ClusterName
      TemplateURL: ./scaling-policy.yml