---
AWSTemplateFormatVersion: 2010-09-09
Description:
  Setting up Slack notification Lambda
Parameters:
  Environment:
    Type         : String
    Default      : Stg
    AllowedValues:
      - Stg
      - Prod
    Description  : Select Environment
    MinLength    : 1
  LambdaCode:
    Type       : String
    Description: Lambda Code
    MinLength  : 1
  LambdaDescription:
    Type       : String
    Description: Lambda Description
    MinLength  : 1
  LambdaHandler:
    Type       : String
    Description: Lambda Handler
    MinLength  : 1
  LambdaExecutionRoleArn:
    Type       : String
    Description: Lambda Execution Role ARN
    MinLength  : 1
  TopicArn:
    Type       : String
    Description: SNS Topic ARN
    MinLength  : 1
Mappings:
  SlackNotificationLambdaFunction:
    Stg :
      ApiUrl: https://hooks.slack.com/services/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
    Prod:
      ApiUrl: https://hooks.slack.com/services/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
Resources:
  # ---------------------------------------------------------------#
  # Create Slack notification Lambda
  # ---------------------------------------------------------------#
  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html
  SlackNotificationLambdaFunction:
    Type      : AWS::Lambda::Function
    Properties:
      Code        : !Ref LambdaCode
      Description : !Ref LambdaDescription
      Environment :
        Variables:
          API_URL: !FindInMap [ SlackNotificationLambdaFunction, !Ref Environment, ApiUrl ]
      Handler     : !Ref LambdaHandler
      Role        : !Ref LambdaExecutionRoleArn
      Runtime     : python3.7
      Timeout     : 60
  SlackNotificationLambdaPermission:
    Type      : AWS::Lambda::Permission
    Properties:
      Action      : lambda:InvokeFunction
      FunctionName: !Ref SlackNotificationLambdaFunction
      Principal   : sns.amazonaws.com
      SourceArn   : !Ref TopicArn
Outputs:
  SlackNotificationLambdaFunctionName:
    Description: The Name of Slack Notification Lambda Funciton
    Value      : !Ref SlackNotificationLambdaFunction
  SlackNotificationLambdaFunctionArn:
    Description: The ARN of Slack Notification Lambda Funciton
    Value      : !GetAtt SlackNotificationLambdaFunction.Arn