---
AWSTemplateFormatVersion: 2010-09-09
Description:
  Setting up ECS API Service Auto Scaling
Parameters:
  ApiTaskMaxCapacity:
    Type       : Number
    Description: Maximum number of API task
    MinValue   : 2
    Default    : 2
  ApiTaskMinCapacity:
    Type       : Number
    Description: Minimum number of API task
    MinValue   : 2
  ECSCluster:
    Type       : String
    Description: ECS Cluster Name
    MinLength  : 1
  ECSApiServiceName:
    Type       : String
    Description: ECS API Service Name
    MinLength  : 1
  ECSAutoScaleRoleArn:
    Type       : String
    Description: ECS Auto Scale Role ARN
    MinLength  : 1
  CPUTargetValue:
    Type       : Number
    Description: Scaling target value of CPU
    Default    : 70
  MemoryTargetValue:
    Type       : Number
    Description: Scaling target value of Memory
    Default    : 70
Resources:
  # ---------------------------------------------------------------#
  # Create Application Auto Scaling ScalableTarget
  # ---------------------------------------------------------------#
  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-applicationautoscaling-scalabletarget.html
  ECSApiServiceAutoScalingScalableTarget:
    Type      : AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity      : !Ref ApiTaskMaxCapacity
      MinCapacity      : !Ref ApiTaskMinCapacity
      ResourceId       : !Sub "service/${ECSCluster}/${ECSApiServiceName}"
      RoleARN          : !Ref ECSAutoScaleRoleArn
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace : ecs
  # ---------------------------------------------------------------#
  # Create Application Auto Scaling ScalingPolicy (About CPU and Memory)
  # ---------------------------------------------------------------#
  # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-applicationautoscaling-scalingpolicy.html
  ECSApiServiceAutoScalingCpuScalingPolicy:
    Type      : AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName                              : CpuScalingPolicy
      PolicyType                              : TargetTrackingScaling
      ScalingTargetId                         : !Ref ECSApiServiceAutoScalingScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        DisableScaleIn               : false
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        TargetValue                  : !Ref CPUTargetValue
  ECSApiServiceAutoScalingMemoryScalingPolicy:
    Type      : AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName                              : MemoryScalingPolicy
      PolicyType                              : TargetTrackingScaling
      ScalingTargetId                         : !Ref ECSApiServiceAutoScalingScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        DisableScaleIn               : false
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageMemoryUtilization
        TargetValue                  : !Ref MemoryTargetValue